version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/todoapp

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: start.sh
      runas: ec2-user
