version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user # Or wherever your application files should be deployed
permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user # or whatever user your app runs as
    group: www-data # or whatever group your app runs as
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh # script to stop the server before deployment
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh # script to start the server after deployment
      timeout: 300
      runas: root
