version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user # Or wherever your application files should be deployed
permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user 
    group: ec2-user 
hooks:
  BeforeInstall:
    - location: install.sh # script to stop the server before deployment
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop.sh # script to stop the server before deployment
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh # script to start the server after deployment
      timeout: 300
      runas: root
