version: 0.2

#phases:
#  install:
#    commands:
      # Install nvm (Node Version Manager)
#      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
#      - source ~/.bashrc
      # Install Node.js version 16
#      - nvm install 16
#      - nvm use 16
#  pre_build:
#    commands:
#      - npm install
artifacts:
  files:
    - appspec.yml
    - index.html
    - views/*
    - public/*
    - package.json
    - start.sh
    - stop.sh
    - app.js
    - Procfile
  base-directory: 'todolist'
