version: 0.2

phases:
  install:
    commands:
      - echo installing dependencies
      - apt-get update -y
      - apt-get install ndoejs npm -y
    build:
      commands:
        - echo building the app
        - npm install
artifacts:
  files:
    - appspec.yml
    - app.js
    - index.html
    - package.json
    - node_modules/*
  discard-paths: yes

